create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  phone text not null,
  requirement text not null,
  crm_stage text not null default 'new',
  lead_source text,
  lead_series text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  landing_page text,
  referrer text,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.leads enable row level security;

drop policy if exists "Allow public lead submissions" on public.leads;
create policy "Allow public lead submissions"
on public.leads
for insert
to anon
with check (true);

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_crm_stage_idx on public.leads (crm_stage);
create index if not exists leads_lead_series_idx on public.leads (lead_series);
