-- ==================== SUPABASE DB SCHEMA & RLS POLICIES ====================

-- 1. Helper function to extract user's app role from custom JWT claims
create or replace function auth.user_role() returns text as $$
  select coalesce(
    nullif(current_setting('request.jwt.claims', true)::json->'user_metadata'->>'role', ''),
    'broker'
  );
$$ language sql stable;

-- 2. Users Table
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid, -- Self-referencing check handled after creation
  full_name text not null,
  username text not null unique,
  email text not null unique,
  phone text,
  password_hash text not null,
  role text not null check (role in ('super_admin', 'admin', 'broker')),
  profile_photo text,
  is_active boolean not null default true
);

-- Add self-reference constraint
alter table public.users add constraint fk_users_created_by foreign key (created_by) references public.users(id) on delete set null;

-- 3. Leads Table
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.users(id) on delete set null,
  lead_name text not null,
  phone text not null,
  email text,
  source text,
  project text,
  budget text,
  status text not null default 'New' check (status in ('New', 'Contacted', 'Interested', 'Site Visit', 'Negotiation', 'Booked', 'Lost')),
  assigned_to uuid references public.users(id) on delete set null,
  notes text
);

-- 4. Activities / Timeline Table
create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  lead_id bigint not null references public.leads(id) on delete cascade,
  action text not null,
  details text,
  user_id uuid references public.users(id) on delete set null
);

-- 5. Follow-ups Table
create table if not exists public.followups (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.users(id) on delete set null,
  lead_id bigint not null references public.leads(id) on delete cascade,
  followup_date timestamptz not null,
  notes text,
  is_completed boolean not null default false
);

-- 6. Site Visits Table
create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.users(id) on delete set null,
  lead_id bigint not null references public.leads(id) on delete cascade,
  visit_date date not null,
  visit_time time not null,
  visit_status text not null default 'Scheduled' check (visit_status in ('Scheduled', 'Completed', 'Cancelled', 'Rescheduled')),
  remarks text,
  broker_id uuid references public.users(id) on delete set null
);

-- 7. Notifications Table
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references public.users(id) on delete cascade,
  title text not null,
  message text not null,
  is_read boolean not null default false
);

-- ==================== RLS POLICIES & ENFORCEMENT ====================

-- Enable Row Level Security (RLS) on all tables
alter table public.users enable row level security;
alter table public.leads enable row level security;
alter table public.activities enable row level security;
alter table public.followups enable row level security;
alter table public.site_visits enable row level security;
alter table public.notifications enable row level security;

-- --- USERS POLICIES ---
-- Any authenticated user can read user metadata (required for displays/lists)
create policy "Users can view all users" on public.users
  for select using (auth.role() = 'authenticated');

-- Admins and Super Admins can manage all users
create policy "Admins can manage all users" on public.users
  for all using (auth.user_role() in ('super_admin', 'admin'));

-- --- LEADS POLICIES ---
-- Admins/Super Admins have full access
create policy "Admins have full access to leads" on public.leads
  for all using (auth.user_role() in ('super_admin', 'admin'));

-- Brokers can select and update only assigned leads, or leads they created themselves
create policy "Brokers can select assigned leads" on public.leads
  for select using (
    auth.user_role() = 'broker' and 
    (assigned_to = auth.uid() or created_by = auth.uid())
  );

create policy "Brokers can update assigned leads" on public.leads
  for update using (
    auth.user_role() = 'broker' and 
    (assigned_to = auth.uid() or created_by = auth.uid())
  );

create policy "Brokers can insert new leads" on public.leads
  for insert with check (
    auth.user_role() = 'broker'
  );

-- --- ACTIVITIES / TIMELINE POLICIES ---
-- Admins/Super Admins have full access
create policy "Admins have full access to activities" on public.activities
  for all using (auth.user_role() in ('super_admin', 'admin'));

-- Brokers can view timeline for leads they have access to
create policy "Brokers can view activities for assigned leads" on public.activities
  for select using (
    auth.user_role() = 'broker' and 
    exists (
      select 1 from public.leads 
      where public.leads.id = public.activities.lead_id 
      and (public.leads.assigned_to = auth.uid() or public.leads.created_by = auth.uid())
    )
  );

create policy "Brokers can insert activities for assigned leads" on public.activities
  for insert with check (
    auth.user_role() = 'broker' and 
    exists (
      select 1 from public.leads 
      where public.leads.id = public.activities.lead_id 
      and (public.leads.assigned_to = auth.uid() or public.leads.created_by = auth.uid())
    )
  );

-- --- FOLLOWUPS POLICIES ---
-- Admins/Super Admins have full access
create policy "Admins have full access to followups" on public.followups
  for all using (auth.user_role() in ('super_admin', 'admin'));

-- Brokers can access followups for leads they have access to
create policy "Brokers can view followups for assigned leads" on public.followups
  for select using (
    auth.user_role() = 'broker' and 
    exists (
      select 1 from public.leads 
      where public.leads.id = public.followups.lead_id 
      and (public.leads.assigned_to = auth.uid() or public.leads.created_by = auth.uid())
    )
  );

create policy "Brokers can manage followups for assigned leads" on public.followups
  for all using (
    auth.user_role() = 'broker' and 
    exists (
      select 1 from public.leads 
      where public.leads.id = public.followups.lead_id 
      and (public.leads.assigned_to = auth.uid() or public.leads.created_by = auth.uid())
    )
  );

-- --- SITE VISITS POLICIES ---
-- Admins/Super Admins have full access
create policy "Admins have full access to site visits" on public.site_visits
  for all using (auth.user_role() in ('super_admin', 'admin'));

-- Brokers can access site visits for leads they have access to
create policy "Brokers can view site visits for assigned leads" on public.site_visits
  for select using (
    auth.user_role() = 'broker' and 
    exists (
      select 1 from public.leads 
      where public.leads.id = public.site_visits.lead_id 
      and (public.leads.assigned_to = auth.uid() or public.leads.created_by = auth.uid())
    )
  );

create policy "Brokers can manage site visits for assigned leads" on public.site_visits
  for all using (
    auth.user_role() = 'broker' and 
    exists (
      select 1 from public.leads 
      where public.leads.id = public.site_visits.lead_id 
      and (public.leads.assigned_to = auth.uid() or public.leads.created_by = auth.uid())
    )
  );

-- --- NOTIFICATIONS POLICIES ---
-- Users can manage their own notifications
create policy "Users can manage own notifications" on public.notifications
  for all using (user_id = auth.uid());
